language: java
jdk: "openjdk8"

install: skip

script: mvn clean compile test jacoco:report

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  slack: fabricalab:UPuOBgojlk1hTI8783gJ8JaV